### ISSUE TITLE
Service worker

### ISSUE THREAD

**Issue by yceffort** [yceffort/yceffort-blog-v2#158]
구버전 서비스워커가 캐시에 남아있어서 현재 페이지가 안열리는 문제 @inbeom

**Comment by inbeom** [comment]
빠른픽스 감사합니다

**Comment by inbeom** [comment]
배포 되었나요? ㅋㅋㅋㅋ 여전히 재현됩니다 ㅠㅠ

**Comment by inbeom** [comment]
앗 새로고침 2번 하니까 회복되었습니다

**Comment by yceffort** [comment]
> 앗 새로고침 2번 하니까 회복되었습니다

헉 ㅋㅋㅋㅋㅋㅋㅋ 이걸 이제봤네요 ㅋㅋㅋ @inbeom 확인요청드리려고 헀는데,,,
수정이 되었다니 다행입니다

감사합니다

좋은하루되세요
행복하세요 ❤️
