### ISSUE TITLE
[Discussion] issue on 2021년 회고

### ISSUE THREAD

**Issue by boxersb** [yceffort/yceffort-blog-v2#477]
https://yceffort.kr/2022/01/2021-retrospective

잘 읽었습니다.. 올해는 좀 더 재미있으시길!!

**Comment by yceffort** [comment]
어이쿠 손님이 오셨군요...! 관심 가져주셔서 감사합니다. 
2022년에도 즐겁게 일할 수 있었으면 좋겠습니다 화이팅입니다 🙇🏻
