### ISSUE TITLE
[Discussion] issue on useEffect는 라이프 사이클 메소드가 아니다.

### ISSUE THREAD

**Issue by silverprize** [yceffort/yceffort-blog-v2#493]
https://yceffort.kr/2020/10/think-about-useEffect
느낌만 있고 말로 정리가 안되던게 이 문장로 정리가 됐네요.
> "결론부터 말하자면, useEffect는 라이프 사이클 훅이 아니다. useEffect는 app 의 state값을 활용하여 동기적으로 부수효과를 만들 수 있는 메커니즘이다."

외부 함수의 경우 주관적이어야 한다고 생각하는데, 
제가 개발한 서비스는 대부분 useEffect안에서 호출하고 현재 상태를 갱신하는 refetch를 제공해야 했기 때문에 useEffect안에서만 호출하게 만들고 끝낼수가 없었어요.

**Comment by yceffort** [comment]
@silverprize 님, 좋은 의견 감사합니다.

개인적으로는 `useEffect`내에서 api 호출이 너무 많은면 사용자 경험에서 부정적인 영향을 미칠 수 있다고 생각합니다. 

컴포넌트를 서비스 단위로 보다 잘게 자르거나, SSR, dynamic import 등 다양한 방법으로 컴포넌트와 useEffect사이를 느슨하게 만들 수도 있을 것 같습니다.

다시한번 관심가져주셔서 감사합니다.
