### ISSUE TITLE
[Discussion] issue on JSX에서 && 대신에 3항 연산자를 더 선호하는 이유

### ISSUE THREAD

**Issue by iicdii** [yceffort/yceffort-blog-v2#527]
https://yceffort.kr/2020/10/use-ternaries-not-and-and-in-jsx

안녕하세요, 최근에 yceffort님 블로그를 알게 되서 재미있게 보고 있는 독자입니다 ㅎㅎ
먼저 글을 보다가 이미지가 엑박 뜨는 문제가 있어서 제보합니다.

---

![screenshot](https://user-images.githubusercontent.com/4951716/161367075-8c2547b9-0c3c-4c72-a32b-e95125e2a3bd.png)

---

그리고, 본문에서 제시하신 방법(`students.length === 0 &&`)도 좋지만  `!students.length &&`와 같이 표현하면 더 짧게 줄일 수 있어서 좋은거 같습니다.
그리고 이번에 React 18이 업데이트 되면서 `undefined` 리턴이 허용되면서 에러에 대한 걱정이 하나 줄어들었습니다. 이 부분에 대한 언급도 있으면 좋지 않을까 싶습니다 ㅎㅎ

> **Components can now render undefined:** React no longer warns if you return `undefined` from a component. This makes the allowed component return values consistent with values that are allowed in the middle of a component tree. We suggest to use a linter to prevent mistakes like forgetting a return statement before JSX.

- Allow components to render undefined. ([#21869](https://github.com/facebook/react/pull/21869) by [@rickhanlonii](https://github.com/rickhanlonii))

**Comment by yceffort** [comment]
안녕하세요! 제보 감사합니다. 🙇🏻

### 이미지 관련

<img width="791" alt="image" src="https://user-images.githubusercontent.com/39641309/161430958-2e7bf45b-8156-4d80-85fc-0a9850728124.png">

 해당 이미지는 수정 처리했습니다. 주기적으로 모든 post들의 이미지를 curl로 찔러서 404를 리턴하는 이미지들에 대해 알려주는 github action을 계획만 하고 있었는데, 이번을 계기로 빨리 만들어야겠다는 생각이 드네요 ^^; 감사합니다.

### number의 falsy 여부 

`students.length === 0 &&` 대신 `!students.length &&` 도 좋은 방법이라고 생각합니다. JS에 익숙하지 않으신분들과 함께 작업하는 경우에는 전자를 쓰는 경우도 있는데, 후자는 말씀하신대로 간결해서 좋습니다.

### React 18 

리액트 18에 대한 내용도 어느정도 인지하고 있어서, 포스팅으로 다뤄볼까 합니다. 다만 리액트 공식 블로그 기준으로 다뤄진 글들은 많이 있어서, 이번엔 CHANGELOG 기준으로 번역해보고 톺아보는 시간을 가져보려고 합니다. 
https://github.com/facebook/react/blob/main/CHANGELOG.md#1800-march-29-2022


@iicdii 님, 변변치 않은 블로그에 의견까지 남겨주셔서 감사합니다. 코시국에 모쪼록 건강챙기시길 바라겠습니다. 감사합니다.

**Comment by iicdii** [comment]
빠른 피드백 반영 감사합니다 🙏 새 글도 기대하겠습니다!
