### ISSUE TITLE
[Discussion] issue on 리액트 v18 버전 톺아보기

### ISSUE THREAD

**Issue by mihilt** [yceffort/yceffort-blog-v2#556]
https://yceffort.kr/2022/04/react-18-changelog

- [x] 겅험 → 경험

:)

**Comment by yceffort** [comment]
@mihilt 님, 오타 수정했습니다. https://github.com/yceffort/yceffort-blog-v2/commit/9606958499500dab0e7581abc32ac2ecb09a1036

누추한 블로그에 관심가셔주셔서 감사합니다. 🙇‍♂️ 좋은 하루 되세요
