### ISSUE TITLE
[Discussion] issue on reduce에 spread 를 쓰면 안되는 이유

### ISSUE THREAD

**Issue by halimsong** [yceffort/yceffort-blog-v2#588]
https://yceffort.kr/2021/06/reduce-spread-anti-pattern

안녕하세요. 글을 보다가 사소한 오타가 발견되어 제보합니다.

https://github.com/yceffort/yceffort-blog-v2/blob/main/posts/2021/06/reduce-spread-anti-pattern.md?plain=1#L101
desuagred => desugared인 것 같습니다.

좋은 글 잘 보고 있습니다. 감사합니다 😃

**Comment by yceffort** [comment]
오타 제보해주셔서 감사합니다. 🙇‍♂️ 확인후 수정하겠습니다. 감사합니다.
