### ISSUE TITLE
[Discussion] issue on 리액트 서버 컴포넌트의 동작 방식  - 동일한 블로그 글이 있군요.

### ISSUE THREAD

**Issue by softuimaster** [yceffort/yceffort-blog-v2#589]
https://yceffort.kr/2022/01/how-react-server-components-work

동일한 글을 발견한것 같은데요.
누군가 선생님글을 번역한것일까요? 

https://www.plasmic.app/blog/how-react-server-components-work

**Comment by yceffort** [comment]
제가 해당 글을 참고한 이후에 어느 정도 제 의견에 맞게 수정했었습니다. 출처가 명확하지 않아서 오해가 있으셨던것 같습니다. 출처 보완하도록 하겠습니다. 감사합니다. 🙇‍♂️
