### ISSUE TITLE
[Discussion] issue on 리액트의 렌더링은 어떻게 일어나는가?

### ISSUE THREAD

**Issue by lee-donghyun** [yceffort/yceffort-blog-v2#599]
https://yceffort.kr/2022/04/deep-dive-in-react-rendering

좋은 글 잘 읽었습니다! 오타를 발견하여 이슈 남깁니다.

`핸들러르르` -> `핸들러를`으로 수정할 수 있을 것 같습니다.

**Comment by yceffort** [comment]
@lee-donghyun 님, 보잘 것 없는 블로그 글에  제보해주셔서 정말 감사합니다.

 머지되어 클로즈하겠습니다. 

날씨가 많이 춥네요. 감기조심하세요!
