### ISSUE TITLE
[Discussion] issue on 블로그 app dir 업그레이드 후기

### ISSUE THREAD

**Issue by carrotpieOwO** [yceffort/yceffort-blog-v2#621]
https://yceffort.kr/05,blog-app-dir

안녕하세요! 혹시 포스팅들이 다 디비에 저장되서 디비에서 불러오도록 되어있으면 이 게시글에 나온 방식으론 동적 사이트맵은 만들지 못하는건가요??

**Comment by yceffort** [comment]
제가 질문을 정확히 이해한건지 모르겠습니다만, 제 예제에서는 빌드 시점에 모든 컨텐츠가 결정되기 떄문에 저렇게 한것이구요.

동적으로 생성하길 원하신다면 위 예제 처럼 `pages/app/sitemap.xml.js` 파일을 만들어 동적으로 사이트 맵을 생성하시는 방법도 있겠네요.

어차피 사이트 맵이라는게 https://yceffort.kr/sitemap.xml 라는 페이지를 만드는 것이라서, appdir에서 위와 같이 xml 형식을 반환하도록 코드를 짜시면 될거같습니다.

**Comment by yceffort** [comment]
감사합니다 😀 좋은 하루 되세요!
