### ISSUE TITLE
[Discussion] issue on 리액트의 렌더링은 어떻게 일어나는가?

### ISSUE THREAD

**Issue by sa02045** [yceffort/yceffort-blog-v2#623]
https://yceffort.kr/04,deep-dive-in-react-rendering

안녕하세요. 늘 블로그 잘 보고있습니다.

블로그 글에 리액트 렌더링관련 오류 글이 있어서 제보드립니다.

<렌더링 프로세스 살펴보기>에 

```
컴포넌트의 렌더링 결과물은 일반적으로 JSX 문법으로 구성되어 있으며, 
이는 js가 컴파일되고 배포 준비가 되는순간에 React.createElement()를 호출하여 변환된다.
```

라고 되어있는데 잘못된 설명인 것 같습니다.

왜냐하면 리액트 컴포넌트 호출 즉, 렌더링은 컴파일 시점이 아닌 `런타임` 시점에 실행됩니다.
그렇기 때문에 컴파일 시점에 React.createElement()를 호출하여 변환하지 않습니다.

아래와 같은 `Count`컴포넌트가 있다고 하면

```js
// Count.js

import { useState } from "react";

function Count() {
  const [count, setCount] = useState(0);
  return (
    <div
      onClick={() => {
        setCount(count + 1);
      }}
    >
      {count}
    </div>
  );
}

export default Count;
```

바벨에 의해서 아래처럼 컴파일 될 것입니다.

```js
// Count.js

import { useState } from "react";
import { jsx as _jsx } from "react/jsx-runtime";
function Count() {
  const [count, setCount] = useState(0);
  return /*#__PURE__*/_jsx("div", {
    onClick: () => {
      setCount(count + 1);
    },
    children: count
  });
}
export default Count;
```

이 컴포넌트는 아직 `호출`되기 전이기 때문에 컴파일시점에 React Element를 생성하여 반환하지 않습니다. 만약 부모 컴포넌트가 아래처럼 사용하고 있어도

```js
import Component from "./Component";

function App() {
  return (
    <div className="App">
      <Component />
    </div>
  );
}
```

부모 컴포넌트 역시 호출되기 전이기 때문에 Child 컴포넌트는 호출되지 않습니다.

런타임에 index.js의 `root.render()`이 호출될때 루트 컴포넌트의 모든 자식 컴포넌트가 렌더링되고 그 React Element를 반환하여 트리를 만듭니다.

그래서 아래와 같은 설명으로 변경되야할 것 같습니다.

```
AS-IS
컴포넌트의 렌더링 결과물은 일반적으로 JSX 문법으로 구성되어 있으며, 
이는 js가 컴파일되고 배포 준비가 되는순간에 React.createElement()를 호출하여 변환된다.


TO-BE
컴포넌트는 일반적으로 JSX 문법으로 구성되어 있으며, 
이는 컴파일 시점에 js로 컴파일되고 런타임에 React.createElement()를 호출하여 React Element로 변환된다.
```

---
 
아직 리액트를 공부중이라 틀릴 수 있습니다.  늘 블로그 양질의 글 잘 보고있습니다.

감사합니다.

**Comment by yceffort** [comment]
지적 감사합니다. 말씀한대로 표현에 오해의 소지가 있었던 것 같습니다. 

(제 기억이 맞다면) 사용자에게 보여지기 전 시점을 의미하는거였던 것 같은데 🤪 말씀해주신 표현이 더 명확하고 정확한 것으로 보입니다. 표현 수정했습니다. https://github.com/yceffort/yceffort-blog-v2/commit/333823c913dbe05d9096a6e5647d4d5d1a8c0729 감사합니다
