### ISSUE TITLE
[Discussion] issue on 새로 바뀐 네이버 메인 훔쳐보기

### ISSUE THREAD

**Issue by armadillo-dev** [yceffort/yceffort-blog-v2#624]
https://yceffort.kr/05,what-is-in-naver

게시물 재미있게 잘 봤습니다~!
한가지 제보 드리면, jquery 사용 여부를 크롬 개발자도구에서 `$('#selector')` 를 찍어보면서 확인하셨는데 
크롬 개발자도구에서 자체 지원하는 것일 수 있습니다.
때문에 확인하신 사항만으로 jquery를 사용하는지는 판단할 수 없습니다.

참고 링크: https://www.bitiniyan.com/2018/12/17/chrome-devtool-tips-aliases/

**Comment by yceffort** [comment]
@armadillo-dev 님, 제보 감사합니다. 🙇‍♂️
혹시 크로미움의 기능일까 해서 파이어폭스, 인터넷 익스플로러 11 등에서 확인해봤는데 모두 동작하는 것 같긴 하더라구요.

## IE 11 `$`

<img width="681" alt="image" src="https://github.com/yceffort/yceffort-blog-v2/assets/39641309/15f7d5ab-100b-48fe-b6d4-ef9e0c2a6bd6">

## firefox `$`

<img width="866" alt="image" src="https://github.com/yceffort/yceffort-blog-v2/assets/39641309/37a9bd91-2c59-48af-9182-22df177f2b6c">

## example.com `$` 과 `jQuery`

확인해보니 확실히 `$`는 크로미움의 기능으로 추정됩니다.

<img width="796" alt="image" src="https://github.com/yceffort/yceffort-blog-v2/assets/39641309/f99674f8-9928-4a81-90b0-8069192c6cb1">


## firefox `jQuery`

네이버에서 다시 확인해보니, jquery가 있긴 한 것 같습니다(?)

<img width="1109" alt="image" src="https://github.com/yceffort/yceffort-blog-v2/assets/39641309/d8ae8678-b360-471b-80db-fd738f20c471">


제보감사합니다. 내용은 수정하도록 하겠습니다. 🙇‍♂️
