### ISSUE TITLE
[Discussion] issue on 왜 Async 보다는 Defer를 써야할까

### ISSUE THREAD

**Issue by taeyoungs** [yceffort/yceffort-blog-v2#628]
https://yceffort.kr/10,defer-than-async

[동기 스크립트는 HTML 구문 분석을 차단한다.](https://yceffort.kr/2020/10/defer-than-async#%EB%8F%99%EA%B8%B0-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%8A%94-html-%EA%B5%AC%EB%AC%B8-%EB%B6%84%EC%84%9D%EC%9D%84-%EC%B0%A8%EB%8B%A8%ED%95%9C%EB%8B%A4)

> 이러한 이유로 인해 앞선 예제에서, 이미지가 다 다운로드 되었음에도 나중에 뵤여지게 된다.

*뵤여지게 => 보이게

오타가 있는 것 같습니다!

블로그 글 너무 잘보고 있습니다.
감사합니다. :)

**Comment by yceffort** [comment]
오타 수정했습니다. 변변찮은 블로그에 많은 관심 가져주셔서 감사합니다 :)
